local colors = {
	variable = "#A7E8FF",
	variable_builtin = "#B7FFF7",
	variable_parameter = "#FFA77B",
	variable_parameter_builtin = "#FF899B",
	variable_member = "#A3BBFF",

	constant = "#FFDF85",
	constant_builtin = "#FFFFFF",
	constant_macro = "#F0F9FF",

	module = "#D6FFAF",
	module_builtin = "#E8C1FF",
	label = "#FFFFFF",

	string = "#D6FFAF",
	string_documentation = "#A7E8FF",
	string_regexp = "#FFA77B",
	string_escape = "#FFDF85",
	string_special = "#E8C1FF",
	string_special_symbol = "#FF899B",
	string_special_url = "#A7E8FF",
	string_special_path = "#A3BBFF",

	character = "#D6FFAF",
	character_special = "#FFA77B",

	boolean = "#FF899B",
	number = "#FFDF85",
	number_float = "#FFA77B",

	type = "#E8C1FF",
	type_builtin = "#D6FFAF",
	type_definition = "#B7FFF7",

	attribute = "#FFDF85",
	attribute_builtin = "#FFFFFF",
	property = "#A7E8FF",

	["function_name"] = "#A7E8FF",
	function_builtin = "#A3BBFF",
	function_call = "#D6FFAF",
	function_macro = "#FFDF85",
	function_method = "#A3BBFF",
	function_method_call = "#A3BBFF",
	constructor = "#FFA77B",

	operator = "#FFFFFF",

	keyword = "#A3BBFF",
	keyword_coroutine = "#A7E8FF",
	keyword_function = "#A3BBFF",
	keyword_operator = "#FFA77B",
	keyword_import = "#E8C1FF",
	keyword_type = "#D6FFAF",
	keyword_modifier = "#FFA77B",
	keyword_repeat = "#FFDF85",
	keyword_return = "#FFDF85",
	keyword_debug = "#FF899B",
	keyword_exception = "#FFA77B",
	keyword_conditional = "#A3BBFF",
	keyword_conditional_ternary = "#FFDF85",
	keyword_directive = "#FFFFFF",
	keyword_directive_define = "#FFFFFF",

	punctuation_delimiter = "#FFFFFF",
	punctuation_bracket = "#A7E8FF",
	punctuation_special = "#FFA77B",

	comment = "#9CA0A8",
	comment_documentation = "#B3BAC8",
	comment_error = "#FF899B",
	comment_warning = "#FFDF85",
	comment_todo = "#D6FFAF",
	comment_note = "#A7E8FF",

	markup_strong = "#FFDF85",
	markup_italic = "#E8C1FF",
	markup_strikethrough = "#FFA77B",
	markup_underline = "#A7E8FF",
	markup_heading = "#A3BBFF",
	markup_heading_1 = "#A3BBFF",
	markup_heading_2 = "#A7E8FF",
	markup_heading_3 = "#A3BBFF",
	markup_heading_4 = "#A7E8FF",
	markup_heading_5 = "#A3BBFF",
	markup_heading_6 = "#A7E8FF",
	markup_quote = "#9CA0A8",
	markup_math = "#FFDF85",
	markup_link = "#A7E8FF",
	markup_link_label = "#B7FFF7",
	markup_link_url = "#A3BBFF",
	markup_raw = "#FFFFFF",
	markup_raw_block = "#9CA0A8",
	markup_list = "#A3BBFF",
	markup_list_checked = "#D6FFAF",
	markup_list_unchecked = "#FFA77B",

	diff_plus = "#D6FFAF",
	diff_minus = "#FF899B",
	diff_delta = "#FFA77B",

	tag = "#A3BBFF",
	tag_builtin = "#A7E8FF",
	tag_attribute = "#FFA77B",
	tag_delimiter = "#FFFFFF",

	none = "#4A5360",
	conceal = "#9CA0A8",

	spell = "#FFA77B",
	nospell = "#9CA0A8",
}

return colors
